Created a graph for the Reports page
Off-Top-App/off-top-flutter pull request #31
Opened 2020-06-23 06:01 UTC by henrydinhd

**What I did:** 
-I created a graph on the Reports tab in the nav bar. The graph shows some static data for your heartbeat and offtop score.

**How to test:** 
-Most of you already know this but you will need Zookeeper, Kafka, Spring-boot, and port forwarding running to log into app.
-Once you are able to log into the app, you just need to click on the reports tab and you will see the graph generate. If you click onto another tab and go back to the reports, it will generate again.

2020-06-23 06:15 UTC, frlzjosh commented on lib/reports.dart
> +class Scores{
can you move this class to its own file in components/graph/scores.dart

2020-06-23 06:21 UTC, frlzjosh commented on lib/reports.dart
> +            child: Container(
move everything starting from the Container() on line 71 to a new file called something like reportsGraph.dart and move it to components/reports/reportsGraph.dart.

Then you can simply import the file in here and pass the class name that you declare in that file like this:


```
body:
   SafeArea(
      child: ReportsGraph()
   )
```

2020-06-23 06:22 UTC, frlzjosh requested changes
Good job, you just need to create components so that we can abstract our code more.

2020-06-23 06:23 UTC, steve545 reviewed
It works and the graph looks cool!

2020-06-23 06:24 UTC, frlzjosh commented on lib/reports.dart
> +            child: Container(
Here are examples of how we've done this in other dart files. 
- https://github.com/Off-Top-App/off-top-flutter/blob/master/lib/recordingSession.dart
- https://github.com/Off-Top-App/off-top-flutter/blob/master/lib/components/recordingSession/meter.dart

2020-06-25 07:17 UTC, frlzjosh requested changes
You have merge conflicts, you need to merge master and fix these before we can approve this PR.

2020-06-26 08:57 UTC, frlzjosh commented on lib/components/reports/reportsGraph.dart
> +                  animationDuration: Duration(seconds: 5),
it's a bit too slow change it to 1.5 seconds if not then change it to 1 second

2020-06-26 09:01 UTC, tonynguyen98 submitted a review, later dismissed
Just a couple easy changes. Was able to build the app and get the graphs to update. Looks great!

2020-06-26 09:01 UTC, tonynguyen98 commented on lib/components/footer/bottomNavigationTabs.dart
> +import '../../reports.dart';
Can you change this to be `package:off_top_mobile/reports.dart `

2020-06-26 09:01 UTC, tonynguyen98 commented on lib/components/reports/reportsGraph.dart
> +      new Scores(5, 60),
With Flutter 1.17, we don't need to use the `new` keyword anymore.

2020-06-26 09:01 UTC, tonynguyen98 commented on lib/components/reports/reportsGraph.dart
> +                  defaultRenderer: new charts.LineRendererConfig(
remove new

2020-06-26 09:01 UTC, tonynguyen98 commented on lib/components/reports/reportsGraph.dart
> +                    new charts.SeriesLegend(
remove new

2020-06-26 09:01 UTC, tonynguyen98 commented on lib/components/reports/reportsGraph.dart
> +                      cellPadding: new EdgeInsets.only(right: 100.0,bottom: 5.0, top: 10.0),
You can use the replace feature to find `new` and replace with an empty space

2020-06-27 08:24 UTC, frlzjosh commented on lib/reports.dart
> +      child: Column(
fix the indentation

2020-06-27 08:25 UTC, frlzjosh requested changes
one small change! Please change mine and tony's requests and your code is good to go!

2020-06-27 08:36 UTC, frlzjosh approved these changes
Great work man!

2020-06-27 08:36 UTC, merged