OT-CreateReportListView | Created a Reports table to show the users data in the reports page
Off-Top-App/off-top-flutter pull request #36
Opened 2020-06-24 10:04 UTC by BigGucciSteve

**What I did:**

- I created a scrollable  table in the reports page to show user reports.

**How to test:**

- Start the zookeeper server.

- Start the kafka server.

- Start Java spring-boot.

- Make sure port forwarding is active.

- Start up the OFF-TOP app.

- Go to the Reports page.

- The Reports table should be shown along with the user reports and the table should be vertically scrollable.

![Capture-1](https://user-images.githubusercontent.com/56651529/85535598-30cbbf80-b5c7-11ea-8832-3ae0013d4467.PNG)

2020-06-25 07:11 UTC, frlzjosh commented on lib/user_report_table.dart
> +        TableRow(children: [
These containers can be moved into a stateless function to get rid of duplicate code. In this function make it of type `Widget` and you can pass two parameters, one being the color, and one is the data
```
Widget getTableData(data, dataColor){
   Container(
            padding: const EdgeInsets.fromLTRB(8.0, 6.0, 8.0, 6.0),
            child: Column(children: [
              Text(color,
                  style: const TextStyle(fontSize: 17, color: dataColor)),
            ]),
          ),
}
```
and then now you can do 
```
rows.add(
   getTableData(rowData.date, Colors.black),
   getTableData(rowData.duration, Colors.black),
   getTableData(rowData.focus, getFocusColor(rowData.focus))
)
```

2020-06-25 07:12 UTC, frlzjosh commented on lib/user_report_table.dart
> +        TableRow(children: [
Move getTableData into  components/reports/getTableDataWidget.dart

2020-06-25 07:14 UTC, frlzjosh commented on lib/user_report_table.dart
> +import 'package:flutter/cupertino.dart';
move the file into components/reports/userReportTable.dart

2020-06-25 07:14 UTC, frlzjosh requested changes
looking good! There are some things that need to moved around and refactored.

2020-06-26 08:22 UTC, tonynguyen98 submitted a review, later dismissed
Just some changes, the app works currently

2020-06-26 08:22 UTC, tonynguyen98 commented on lib/components/footer/bottomNavigationTabs.dart
> +import '../../reports.dart';
Can you change this import of this to `package:off_top_mobile/reports.dart` in the event where we need to move the file, it'll be easier to change?

2020-06-26 08:22 UTC, tonynguyen98 commented on lib/user_report_table.dart
> +    }
Can you move all these out of the build Widget and into it's own Widget?

2020-06-26 10:19 UTC, frlzjosh approved these changes
looks good! Great job!

2020-06-26 10:19 UTC, merged