OT-FocusVibration | Added vibration for when the focus score is false
Off-Top-App/off-top-flutter pull request #43
Opened 2020-07-11 05:59 UTC by henrydinhd

**What I did**: To be able to trigger a vibration and print statement when the focus score is false.

**How to test**: 
-Have the off-top app running
-Have producer.py in off-top-python running
-Start recording so the app can get your focus score. The emulator itself will not show vibration unless you are testing it on a real device, but I've added a print statement so when the focus score is false, it will print out "medium impact vibration" in the off-top-flutter terminal.
![Screenshot (44)](https://user-images.githubusercontent.com/55634110/87217677-c1610a00-c300-11ea-8ef6-d065b1ca905b.png)
![Screenshot (45)](https://user-images.githubusercontent.com/55634110/87217679-c45bfa80-c300-11ea-8958-098ec92151ec.png)

2020-07-12 09:12 UTC, frlzjosh commented on lib/components/recordingSession/meter.dart
>        () {
wrap this into a method

2020-07-12 09:13 UTC, frlzjosh commented on lib/components/recordingSession/vibration.dart
> +    print('medium impact vibration');
there's a lot of extra lines in this file we don't need, can you delete them?

2020-07-12 09:28 UTC, frlzjosh requested changes
Very small changes. but this is looking really good!

2020-07-12 09:28 UTC, frlzjosh commented on lib/components/recordingSession/vibration.dart
> +    print('medium impact vibration');
can you change the print statement to be "Read Low Focus Score"

2020-07-12 21:08 UTC, tonynguyen98 commented
Was able to test on a physical Android device and it's working as intended.

2020-07-15 00:54 UTC, BigGucciSteve commented
worked for me on my end nice job!

2020-07-15 00:55 UTC, steve545 reviewed
worked for me on my end nice job!

2020-07-15 04:03 UTC, frlzjosh commented on lib/components/recordingSession/meter.dart
>        () {
call it something like `determineMeterScore()`

2020-07-15 04:54 UTC, frlzjosh approved these changes
nice man!

2020-07-15 04:54 UTC, merged