OT-MigrateFlutterEndpoints | Migrate flutter to be hitting our newly created microservices
Off-Top-App/off-top-flutter pull request #48
Opened 2020-07-14 09:48 UTC by frlzjosh

**WHAT I DID:**
1. Migrated flutter to be hitting our newly created microservices. 
2. Also updated the User object so that it passes the properly named attribute of `profession` instead of `professional`
3.  No longer passing `password` to the backend anymore as it is not required in the User microservice and no longer exists as a column in the user MySQL table

HOW TO TEST:
1. Run Kafka/Zookeeper, [UserService](https://github.com/Off-Top-App/UserService), & SessionHandler(https://github.com/Off-Top-App/SessionHandlerService)
2. Make sure that you can create an account and login
3. Be able to send audio data to the WebSocket in SessionHandlerService

2020-07-19 22:31 UTC, tonynguyen98 requested changes
Great work, just one single change needed

2020-07-19 22:31 UTC, tonynguyen98 commented on lib/components/recordingSession/websocket.dart
> +      String exportedAudioData, int userID, String topic, String time_exported) async {
Can you make `time_exported` to camel case `timeExported`

2020-07-19 22:31 UTC, tonynguyen98 commented on lib/components/recordingSession/websocket.dart
> +        {'audio_data': audioData, 'user_id': userID.toInt(), 'topic': topic, 'time_exported': time_exported},
change to `'time_exported': timeExported`

2020-07-20 00:38 UTC, tonynguyen98 approved these changes
Great work, lots of great updates

2020-07-20 04:01 UTC, txt020 approved these changes

2020-07-20 04:01 UTC, txt020 commented on lib/services/userService.dart
> +  }
Looks Good!

2020-07-20 04:01 UTC, txt020 commented on lib/accountCreation.dart
> +      null,
Why is there a Null here?

2020-07-20 04:30 UTC, frlzjosh commented on lib/accountCreation.dart
> +      null,
because we don't have the team their account was deleted at.

2020-07-20 04:32 UTC, merged